spring:
  profiles:
    active: local

jwt:
  token:
    header: api_key
    issuer: wanni_market
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 6000
---
#local 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wannimart?serverTimezone=Asia/Seoul
    username: wanni
    password: wanni0928

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug # logger 로 출력
    org.hibernate.type: trace # 쿼리 파라미터 로그 출력

---
#dev 환경
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.SQL: info # logger 로 출력
    org.hibernate.type: trace # 쿼리 파라미터 로그 출력
---