spring:
  profiles:
    active: dev
  application:
    name: wannimart
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    url: ENC(aaUDaoLUn91Vhg457iWMTASha0kylHdnpxZPJ2KLhAN9/itmthHQ1+HGW46F3vWvzoJogv3Do4U=)
    username: ENC(YOO5zgr7tPSGxcnmQwmVzw==)
    password: ENC(kfi0ALvluj1quiX14KKtAIU6StSmeS1S)

jwt:
  token:
    header: api_key
    issuer: wanni_market
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 6000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
---
#local 환경
spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug # logger 로 출력
    org.hibernate.type: trace # 쿼리 파라미터 로그 출력

---
#dev 환경
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.SQL: info # logger 로 출력
---