spring:
  application:
    name: wannimart
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    url:
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


logging:
  level:
    org:
      hibernate:
        SQL: off
      springframework:
        web: DEBUG

server:
  error:
    include-message: ALWAYS
    include-stacktrace: never
jwt:
  token:
    header: api_key
    issuer: wanni_market
    clientSecret:
    expirySeconds: 6000